version: "3.8"

services:
  ecommerceDBPostgres15:
    image: postgres:15
    container_name: ecommerceDBPostgres15
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
